apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::375669694671:role/test-oidc
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: aws-test
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      limits:
        cpu: "0.5"  # limit CPU usage to 0.5 cores
        memory: "512Mi"  # limit memory usage to 512 MiB
      requests:
        cpu: "0.1"  # request a minimum of 0.1 cores
        memory: "256Mi"  # request a minimum of 256 MiB
  tolerations:
  - operator: Exists
    effect: NoSchedule